name: ğŸš¦ client-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›« Check out code #sert Ã  rÃ©cupÃ©rer le code du repo sur lequel le workflow est lancÃ©
        uses: actions/checkout@v2 #On utilise une action qui nous est fournie par Github, on spÃ©cifie donc le nom de l'action, avec le mot clef uses

      - name: ğŸƒğŸ½ Go to client and run tests # permet de nous rendre dans le dossier oÃ¹ se trouve le code du client, d'installer les dÃ©pendances et de lancer les tests
        run: cd ../client && npm i && npm test